version: '3.8'

services:
  api:
    build: .
    container_name: geolocation_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - geolocation_network

  db:
    image: postgres:14
    container_name: geolocation_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geolocation_network

volumes:
  postgres_data:

networks:
  geolocation_network:
    driver: bridge