version: '3.8'

services:
  api:
    build: .
    container_name: geolocation_api
    volumes:
      - .:/app  # Mount local files inside the container
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - geolocation_network

  db:
    image: postgres:14
    container_name: geolocation_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geolocation_network

volumes:
  postgres_data:

networks:
  geolocation_network:
    driver: bridge