version: '3.8'

services:
  api:
    build: .
    container_name: geolocation_api
    volumes:
      - .:/app  # Mount local files inside the container
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Wait for the database to be healthy
    networks:
      - geolocation_network

  db:
    image: postgres:14
    container_name: geolocation_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - geolocation_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  geolocation_network:
    driver: bridge